---
abstract: 'Toolkit for managing production Galaxy server instances'
author:
  - 'Jeremy Volkening <jdv@base2bio.com>'
build_requires:
  File::ShareDir: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-Galaxy-Toolkit
provides:
  Bio::Galaxy::Toolkit:
    file: lib/Bio/Galaxy/Toolkit.pm
  Bio::Galaxy::Toolkit::Command:
    file: lib/Bio/Galaxy/Toolkit/Command.pm
  Bio::Galaxy::Toolkit::Command::adduser:
    file: lib/Bio/Galaxy/Toolkit/Command/adduser.pm
requires:
  App::Cmd: '0'
  Bio::Galaxy::API: '0'
  Email::Valid: '0'
  File::ShareDir: '1.00'
  IO::Socket::SSL: '0'
  Net::Domain: '0'
  Net::SMTP: '0'
  YAML::Tiny: '0'
resources:
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/jvolkening/galaxy_toolkit
version: '0.002'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
